const variants = {
  'Checkout - Scroll': ['scroll-v1', 'scroll-v2', 'scroll-v3'],
  'Checkout - Above the Fold': ['atf-v1', 'atf-v2', 'atf-v3'],
  'Ecom - Scroll': ['ecom-scroll-v1', 'ecom-scroll-v2', 'ecom-scroll-v3'],
  'Ecom - Above the Fold': ['ecom-atf-v1', 'ecom-atf-v2', 'ecom-atf-v3'],
} as const;

const subjects = ['sat', 'act', 'chem', 'calc', 'reading'] as const;

export default function LandingIndex() {
  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-5xl mx-auto">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">
          Checkout Landing Page Variants
        </h1>
        <p className="text-gray-500 mb-10">
          12 variants &times; 5 subjects = 60 landing pages
        </p>

        {Object.entries(variants).map(([groupName, variantList]) => (
          <section key={groupName} className="mb-10">
            <h2 className="text-xl font-semibold text-gray-800 mb-4 border-b border-gray-200 pb-2">
              {groupName}
            </h2>
            <div className="grid gap-4">
              {variantList.map((variant) => (
                <div key={variant} className="bg-white rounded-lg shadow-sm p-4">
                  <h3 className="text-sm font-mono font-medium text-indigo-600 mb-3">
                    {variant}
                  </h3>
                  <div className="flex flex-wrap gap-2">
                    {subjects.map((subject) => (
                      <a
                        key={subject}
                        href={`/landing/${variant}/${subject}`}
                        className="inline-flex items-center px-3 py-1.5 rounded-md text-sm font-medium bg-indigo-50 text-indigo-700 hover:bg-indigo-100 transition-colors"
                      >
                        {subject.toUpperCase()}
                      </a>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          </section>
        ))}

        <footer className="mt-12 pt-6 border-t border-gray-200 text-center text-sm text-gray-400">
          Generated by Ralph - Checkout Experience Variants
        </footer>
      </div>
    </div>
  );
}
